location: centralindia
apiVersion: 2023-05-01
name: courses-group
type: Microsoft.ContainerInstance/containerGroups
properties:
  osType: Linux
  ipAddress:
    type: Public
    ports:
      - protocol: Tcp
        port: 80
  containers:
    - name: mysql
      properties:
        image: sgfrozengoods-gac7aeckefa4gja0.azurecr.io/frzdb1:1.0 
        resources: { requests: { cpu: 0.5, memoryInGB: 1.5 } }
        ports: [ { protocol: Tcp, port: 3306 } ]
    - name: php
      properties:
        image: sgfrozengoods-gac7aeckefa4gja0.azurecr.io/frzapp:1.0.1 
        resources: { requests: { cpu: 0.5, memoryInGB: 0.5 } }
        ports: [ { protocol: Tcp, port: 80 } ]

  imageRegistryCredentials:
    - server: sgfrozengoods-gac7aeckefa4gja0.azurecr.io
      username: SGfrozengoods
      password: "8uzb7SFf6vYluHGHmqqc5648YYW3LdPVj1AJZXyjmjwQQdGXlBMyJQQJ99CDACGhslBEqg7NAAACAZCRNd42"