name: Docker Image CI

on:
  push:
    paths:
      - "retail_app/**"
  pull_request:
    paths:
      - "retail_app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}   
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -f retail_app/dockerfile.yml \
            -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/retail_app:1.0.0 \
            -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/retail_app:${{ github.sha }} \
            ./retail_app

      - name: Push image
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/retail_app:1.0.0
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/retail_app:${{ github.sha }}

