name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build Docker image
        run: docker build -f retail_app/Dockerfile \
          -t retail_app:1.0.0 \
          -t azacrimg:$(date +%s) \
          ./retail_app
